### PR TITLE
Add staging of enchantments

### PR DESCRIPTION
**Pull request by sk2048**
Due to a change in how JEI handles enchantments, staging enchanted books would not hide them from JEI.

To resolve this, I have added a separate "stageEnchant" zenscript method, which removes the enchantment "ingredient" from JEI when a player does not have the stage, adding it back when the player has the relevant stage.

Additionally, enchanted books with the relevant enchantment are staged as items, thus marking them as unfamiliar.

### CODE REVIEW

**Comment by sk2048** [comment]
The changes included in this pull request have changed substantially since I made it. It no longer deals with JEI directly as the issue with hiding of enchanted books has been resolved on their end.

Instead it focuses on staging items that have enchantments, preventing players from making use of enchanted items before unlocking the corresponding stage.

A tool with an enchantment not yet unlocked will not be able to break blocks. A weapon will not be able to deal damage. Armour cannot be equipped.

By default, an enchanted item that a player cannot use will not be dropped. I added a config option to change this.

The following line caused me confusion, I believe in the first operation it checks the wrong tag to be empty. I may however have got the wrong end of the stick and wanted to flag that I had made this change.
https://github.com/Darkhax-Minecraft/ItemStages/blob/master/src/main/java/net/darkhax/itemstages/StageCompare.java#L24

I hope you feel this is a useful addition to this mod, and any feedback will be appreciated!

**Comment by darkhax** [comment]
Thanks for the updates. Is this PR still being worked on? I noticed there is quite a bit of commented out code.

**Comment by sk2048** [comment]
Small bit more work to be done, I'll probably get time for it early next week. Commented code relates to hiding of enchantment ingredients in JEI, which is now done by JEI if the enchanted book is hidden.

**Comment by sk2048** [comment]
I've done as much work on this as I have the time for at present. @darkhax, I hope you find this useful.

**Pull request merged**
