### PR TITLE
Update to 1.18.2

### PR DESCRIPTION
**Pull request by remplerus**
simple update to forge 1.18.2 (not sure if you want to make ItemStages available on Fabric too, but this is just a simple update), also there's no 1.18 branch, therefore i use 1.16.5 as base.

- tested example_scripts on singleplayer, working fine
- tested example_scripts in multiplayer, working fine
- moved from log4j to slf4j (can be easily undone by changing Logger and LoggerFactory back to log4j)

### CODE REVIEW

**Comment by vizthex123** [comment]
A 1.19.2 version of this and Recipe Stages would be great too.

**Comment by BelgianDev** [comment]
@remplerus You should ask Darkhax if you can create you're own CurseForge page and continue support the mod with fixes and updates, this mod is dead so it will be realy nice to continue it just for modpack creators. Please

**Comment by Darkhax** [comment]
@Raft08 The mod is not dead. I've asked people on the Discord to test this update and have been waiting on their feedback.

**Comment by Darkhax** [comment]
Thank you @remplerus for helping out with this PR. I am sorry for the lack of communication with you on this and the slow review process in general. I really appreciate your help.

**Comment by vizthex123** [comment]
So, anyone got an ETA on a 1.19.2 version?

Not trying to rush y'all or anything ofc, but I figured I might as well ask.

**Pull request merged**
